#错误码配置
errorCode:
  "0002":  "非法登录"
  "0001":  "用户名或密码错误"
  "0003":  "服务器异常"
  10000:  "未知的event"
  10001:  "未知的pair"
  10008:  "并发错误"
  10020:  "请求参数错误"
  10050:  "配置信息设置错误"
  10100:  "验证失败"
  10111:  "认证请求payload出错"
  10112:  "认证请求signature出错"
  10113:  "认证请求encryption出错"
  10114:  "认证请求nonce出错"
  10200:  "取消认证请求时出错"
  10300:  "订阅失败(订阅时的返回)"
  10301:  "重复订阅"
  10302:  "未知的channel"
  10400:  "订阅失败(取消订阅时的返回)"
  10401:  "没有订阅"
  11000:  "未准备好，请稍后再试"
  20051:  "Websocket server stopping... please reconnect later"
  20060:  "Websocket server resyncing... please reconnect later"
  20061:  "Websocket server resync complete. please reconnect"
  5000:  "info message"